### ISSUE TITLE
Расположение  основной ветки

### ISSUE THREAD

**Issue by bonvech** [VPlotnikov2006/bot_generator#18]
Основное текущее состояние должно быть расположено в корне основного репозитория, а не это вот всё... 
Мало того, что "ищи в форке", так еще и не в основной ветке... Бардак! И они ещё претендуют на звание "Мы сделали это!"

**Comment by VPlotnikov2006** [comment]
Наша компания приносит извинения за несанкционированные действия одного сотрудника. В течении дня будет проведена разъяснительная беседа. Наш проект не претендует на звание "Мы сделали это!". Искать в форке ничего не надо т.к. основной репозиторий сейчас обладает самой актуальной версией, а сотрудники. Ветка realisation пока что не до конца протестирована и не может быть слита в main.

**Comment by bonvech** [comment]
Спасибо за быстрый и четкий ответ! 
Наш небольшой коллектив авторов будущих текстовых квестов с нетерпением ждет выхода протестированной версии вашего шедевра, а пока довольствуется разрекламированным форком.
