### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by LogosITO** [VPlotnikov2006/bot_generator#23]
Файл bot.py не работает: возникает следующая ошибка:
ModuleNotFoundError: No module named 'TelegramBotData.inventory'
Возможная причина:
Устаревший init(он пытается открыть TelegramBotData.inventory и TelegramBotData.config)

**Comment by VPlotnikov2006** [comment]
Спасибо за ваш вклад в развитие проекта.
Баг устранен в последнем релизе
